name: Deploy Storage Worker

on:
  push:
    branches: [main]
    paths:
      - 'apps/storage/**'
  pull_request:
    branches: [main]
    paths:
      - 'apps/storage/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Storage Worker
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'apps/storage/package-lock.json'

      - name: Install dependencies
        run: |
          cd apps/storage
          npm ci

      - name: Deploy to Staging
        if: github.event_name == 'pull_request'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env staging
          workingDirectory: 'apps/storage'
        env:
          DEBUG_PASSWORD: ${{ secrets.DEBUG_PASSWORD_STAGING }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env production
          workingDirectory: 'apps/storage'
        env:
          DEBUG_PASSWORD: ${{ secrets.DEBUG_PASSWORD_PRODUCTION }}